#! /bin/bash

function is_hex_ {
    [[ "$1" =~ ^[0-9A-Fa-f]{6}$ ]]
}

function is_commit_() {
    [[ "$1" =~ ^[0-9a-f]{40}$ ]]
}

function is_version_() {
    [[ "$1" =~ ^([<=>~^!]*[0-9]+(\.[0-9]+)*(\.[0-9]+)?(\.[0-9]+)?)$ ]]
}

