#! /bin/bash

_make_completion() {
    if [[ ! -f Makefile ]]; then
        return
    fi

    local targets
    targets=$(grep -E '^[^#[:space:]].*:' Makefile | cut -d':' -f1 | sort | uniq)

    COMPREPLY=( $(compgen -W "$targets" -- "${COMP_WORDS[1]}") )
}

complete -F _make_completion make
